import {
    IconBrandGoogle,
    IconBrandTwitter,
    IconBrandGithub,
    IconBrandInstagram,
    IconBrandYoutube,
    IconBrandOpenai,
    IconBrandDiscord,
    IconBrandNetflix,
    IconBrandSpotify,
    IconBrandWindows,
    IconNetwork,
    IconBrandApple,
    IconBrandTelegram,
} from '@tabler/icons-react'

export interface ServiceData {
    name: string
    domainPatterns: string[]
    icon: React.FC<any>
}

export const ALL_SERVICES: ServiceData[] = [
    {
        name: 'Apple TV+',
        domainPatterns: [
            'tv.apple.com',
            'video.apple.com',
            'v.apple.com',
            'play.itunes.apple.com',
            'aod.itunes.apple.com',
            'vod-akc.apple.com',
            'cvp.cloudfront.net',
        ],
        icon: IconBrandApple,
    },
    {
        name: 'Discord',
        domainPatterns: [
            'dis.gd',
            'discord-activities.com',
            'discord.co',
            'discord.com',
            'discord.design',
            'discord.dev',
            'discord.gift',
            'discord.gifts',
            'discord.gg',
            'discord.media',
            'discord.new',
            'discord.store',
            'discord.tools',
            'discordapp.com',
            'discordapp.net',
            'discordmerch.com',
            'discordpartygames.com',
            'discordsays.com',
            'discordstatus.com',
        ],
        icon: IconBrandDiscord,
    },
    {
        name: 'GitHub',
        domainPatterns: [
            'github.com',
            'api.github.com',
            'gist.github.com',
            'githubusercontent.com',
            'api.individual.githubcopilot.com',
            'githubcopilot.com',
            'copilot-proxy.githubusercontent.com',
            'copilot-telemetry.githubusercontent.com',
            'default.exp-tas.com',
            'education.github.com',
            'origin-tracker.githubusercontent.com',
        ],
        icon: IconBrandGithub,
    },
    {
        name: 'Google',
        domainPatterns: [
            'bard.google.com',
            'calendar.google.com',
            'drive.google.com',
            'docs.google.com',
            'gemini.google.com',
            'google.com',
            'googleapis.com',
            'googlecode.com',
            'googleoptimize.com',
            'googleusercontent.com',
            'googleweblight.in',
            'gstatic.com',
            'mail.google.com',
            'maps.google.com',
            'meet.google.com',
            'news.google.com',
            'photos.google.com',
            'play.google.com',
            'translate.google.com',
            'sites.google.com',
            'scholar.google.com',
            'keep.google.com',
            'hangouts.google.com',
            'myaccount.google.com',
            'groups.google.com',
            'console.developers.google.com',
            'support.google.com',
            'cloud.google.com',
            'gvt2.com',
        ],
        icon: IconBrandGoogle,
    },
    {
        name: 'IP Check',
        domainPatterns: [
            '2ip.ru',
            'addr.tools',
            'browserleaks.com',
            'dnsleaktest.com',
            'myip.addr.tools',
            'myip2.ru',
            'ifconfig.me',
        ],
        icon: IconNetwork,
    },
    {
        name: 'Instagram',
        domainPatterns: [
            'facebook.com',
            'ig.me',
            'instagram.com',
            'cdninstagram.com',
            'static.cdninstagram.com',
            'meta.com',
        ],
        icon: IconBrandInstagram,
    },
    {
        name: 'Microsoft',
        domainPatterns: ['live.com', 'microsoft.com', 'microsoft365.com'],
        icon: IconBrandWindows,
    },
    {
        name: 'Netflix',
        domainPatterns: ['netflix.com', 'fast.com'],
        icon: IconBrandNetflix,
    },
    {
        name: 'OpenAI',
        domainPatterns: [
            'ab.chatgpt.com',
            'api.openai.com',
            'arena.openai.com',
            'auth.openai.com',
            'auth0.openai.com',
            'beta.api.openai.com',
            'beta.openai.com',
            'blog.openai.com',
            'cdn.oaistatic.com',
            'cdn.openai.com',
            'community.openai.com',
            'contest.openai.com',
            'debate-game.openai.com',
            'discuss.openai.com',
            'files.oaiusercontent.com',
            'gpt3-openai.com',
            'gym.openai.com',
            'help.openai.com',
            'ios.chat.openai.com',
            'jukebox.openai.com',
            'labs.openai.com',
            'microscope.openai.com',
            'oaistatic.com',
            'openai.com',
            'openai.fund',
            'openai.org',
            'platform.api.openai.com',
            'platform.openai.com',
            'spinningup.openai',
            'chat.openai.com',
            'chatgpt.com',
            'sora.com',
        ],
        icon: IconBrandOpenai,
    },
    {
        name: 'Spotify',
        domainPatterns: [
            'audio-ak-spotify-com.akamaized.net',
            'audio4-ak-spotify-com.akamaized.net',
            'cdn-spotify-experiments.conductrics.com',
            'heads-ak-spotify-com.akamaized.net',
            'heads4-ak-spotify-com.akamaized.net',
            'scdn.co',
            'spoti.fi',
            'spotify-everywhere.com',
            'spotify.com',
            'spotify.design',
            'spotify.map.fastly.net',
            'spotify.map.fastlylb.net',
            'spotify.com.edgesuite.net',
            'spotifycharts.com',
            'spotifycodes.com',
            'spotifycdn.com',
            'spotifycdn.net',
            'spotifyforbrands.com',
            'spotifyjobs.com',
        ],
        icon: IconBrandSpotify,
    },
    {
        name: 'Telegram',
        domainPatterns: [
            'cdn-telegram.org',
            'comments.app',
            'contest.com',
            'fragment.com',
            'graph.org',
            'quiz.directory',
            't.me',
            'tdesktop.com',
            'telega.one',
            'telegra.ph',
            'telegram-cdn.org',
            'telegram.dog',
            'telegram.me',
            'telegram.org',
            'telegram.space',
            'telesco.pe',
            'tg.dev',
            'tx.me',
            'usercontent.dev',
            '149.154.160.0/20',
            '91.108.4.0/22',
            '91.108.56.0/22',
            '91.108.8.0/22',
            '95.161.64.0/20',
        ],
        icon: IconBrandTelegram,
    },
    {
        name: 'Twitter & X',
        domainPatterns: [
            'abs-0.twimg.com',
            'abs.twimg.com',
            'analytics.x.com',
            'api-stream.twitter.com',
            'api.twitter.com',
            'mobile.twitter.com',
            'pbs.twimg.com',
            't.co',
            'ton.twitter.com',
            'twimg.com',
            'twitpic.com',
            'twitter.co',
            'twitter.com',
            'video.twimg.com',
            'x.com',
        ],
        icon: IconBrandTwitter,
    },
    {
        name: 'YouTube',
        domainPatterns: [
            'googlevideo.com',
            'yt3.ggpht.com',
            'youtube.com',
            'i.ytimg.com',
            'youtubei.googleapis.com',
            'yt3.googleusercontent.com',
            'm.youtube.com',
            'google.com',
            'www.google.com',
            'googleapis.com',
            'gstatic.com',
            'play.google.com',
            's.youtube.com',
            'www.youtube.com',
            'youtu.be',
            'ggpht.com',
            'ytimg.com',
            'nhacmp3youtube.com',
            'googleusercontent.com',
            'connectivitycheck.gstatic.com',
            'l.google',
        ],
        icon: IconBrandYoutube,
    },
]
