services:
  sphinx-html:
    build:
        dockerfile: Dockerfile
    image: "sphinxdoc/sphinx"
    volumes:
      - "${PWD}:/docs"
    user: "${UID}:${GID}"
    working_dir: /docs
    command: >
        /bin/bash -c "make html && touch /docs/html_done"

  sphinx-epub:
    build:
        dockerfile: Dockerfile
    image: "sphinxdoc/sphinx"
    volumes:
      - "${PWD}:/docs"
    user: "${UID}:${GID}"
    working_dir: /docs
    command: >
        /bin/bash -c "make epub && touch /docs/epub_done"


  sphinx-pdf:
    build:
        dockerfile: Dockerfile.latex
    image: "sphinxdoc/sphinx-latexpdf"
    volumes:
      - "${PWD}:/docs"
    user: "${UID}:${GID}"
    working_dir: /docs
    command: >
        /bin/bash -c "make latexpdf && touch /docs/pdf_done"

  post-build-clean:
    image: "sphinxdoc/sphinx"
    depends_on:
      - sphinx-html
      - sphinx-epub
      - sphinx-pdf
    volumes:
      - "${PWD}:/docs"
    user: "${UID}:${GID}"
    working_dir: /docs
    entrypoint: sh -c "
          while [ ! -f /docs/html_done ] || [ ! -f /docs/epub_done ] || [ ! -f /docs/pdf_done ]; do
            echo 'Ожидаем завершения всех сборок...';
            sleep 2;
          done;
          make clean;
          rm /docs/html_done /docs/epub_done /docs/pdf_done;"
