name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Modify BrowserRouter to HashRouter and change homepage
        working-directory: "client"
        run: |
          sed -i 's/BrowserRouter/HashRouter/' src/index.tsx
          sed -i 's|"homepage": ".*"|"homepage": "https://dan0102dan.github.io/kvas-wui"|' package.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: "client"
        run: npm install

      - name: Build and deploy
        working-directory: "client"
        run: |
          npm run build
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "GitHub Pages deployment"
          git push origin HEAD:gh-pages --force
          
      - name: Check version and create tag if needed
        working-directory: "client"
        run: |
          git fetch --tags
          VERSION=$(jq -r '.version' package.json)
          echo "Current version: $VERSION"

          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Skipping tag creation."
          else
            echo "Tag v$VERSION not found. Creating tag."
            git tag "v$VERSION"
            git push origin "v$VERSION"
          fi