name: Build Release

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies
        working-directory: client
        run: npm ci --prefer-offline

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Create frontend archive
        run: tar -czf build.tar.gz -C client/build .

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: build.tar.gz
          path: build.tar.gz

  build_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [mipsle, mips, arm64]
        include:
          - goarch: mipsle
            goos: linux
            output: api-mipsel
          - goarch: mips
            goos: linux
            output: api-mips
          - goarch: arm64
            goos: linux
            output: api-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        working-directory: server
        with:
          go-version: '1.23'

      - name: Build binary
        working-directory: server
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -trimpath -ldflags="-s -w" -o ../${{ matrix.output }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  create_release:
  needs: [build_frontend, build_backend]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
        fetch-tags: true

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-assets
        merge-multiple: true

    - name: Fetch all tags
      run: git fetch --tags --force

    - name: Check tag
      id: tag_check
      run: |
        TAG=$(git tag --points-at ${{ github.event.workflow_run.head_sha }})
        if [ -z "$TAG" ]; then
          echo "tag_exists=false" >> $GITHUB_OUTPUT
        else
          echo "tag_exists=true" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      if: steps.tag_check.outputs.tag_exists == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_check.outputs.tag }}
        files: release-assets/*