name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_archive: ${{ steps.upload-frontend.outputs.artifact }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Create frontend archive
        run: tar -czvf build.tar.gz -C client .

      - name: Upload frontend artifact
        id: upload-frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build.tar.gz

  build_backend:
    needs: build_frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - mipsle
          - mips
          - arm64
        include:
          - goarch: mipsle
            goos: linux
            output: api-mipsel
          - goarch: mips
            goos: linux
            output: api-mips
          - goarch: arm64
            goos: linux
            output: api-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Build Go binary
        working-directory: server
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go mod tidy
          go build -o ../${{ matrix.output }}

      - name: Upload Go binary
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ matrix.goarch }}  # Уникальное имя для каждой архитектуры
          path: ${{ matrix.output }}

  create_release:
    needs: [build_frontend, build_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: release-assets

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: backend-*
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-assets/*