name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies
        working-directory: client
        run: npm ci --prefer-offline

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Create frontend archive
        run: tar -czf build.tar.gz -C client/build .

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: build.tar.gz
          path: build.tar.gz

  build_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [mipsle, mips, arm64]
        include:
          - goarch: mipsle
            goos: linux
            output: api-mipsel
          - goarch: mips
            goos: linux
            output: api-mips
          - goarch: arm64
            goos: linux
            output: api-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build binary
        working-directory: server
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -trimpath -ldflags="-s -w" -o ../${{ matrix.output }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  create_release:
    needs: [build_frontend, build_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: release-assets
          merge-multiple: true

      - name: List artifacts
        run: ls -la release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-assets/api-*
            release-assets/build.tar.gz